services:
  pokedex_db:
    image: postgres:13-alpine
    container_name: pokedex_db
    restart: always
    env_file:
      - .env
    volumes:
      - pokedex_db:/var/lib/postgresql
    ports:
      - 5433:5432
    networks:
      - pokedex_network
  pokedex_api:
    build: .
    container_name: pokedex_api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - pokedex_db
    networks:
      - pokedex_network

networks:
  pokedex_network:
    driver: bridge
    name: pokedex_network
    external: true
volumes:
  pokedex_db:
    external: true
