UPDATE "move" SET "flavorText"='The user converts its rage into energy to attack. The more times the user has been hit by attacks, the greater the move''s power.' WHERE "name" = 'rage-fist';
UPDATE "move" SET "flavorText"='The user tidies up and removes the effects of Spikes, Stealth Rock, Sticky Web, Toxic Spikes, and Substitute. This also boosts the user''s Attack and Speed stats.' WHERE "name" = 'tidy-up';
UPDATE "move" SET "flavorText"='null' WHERE "name" = 'noxious-torque';
UPDATE "move" SET "flavorText"='The user attacks by pouncing on the target. This also lowers the target''s Speed stat.' WHERE "name" = 'pounce';
UPDATE "move" SET "flavorText"='The user covers its feet in thin ice and twirls around, slamming into the target. This move''s spinning motion also destroys the terrain.' WHERE "name" = 'ice-spinner';
UPDATE "move" SET "flavorText"='The user sharply boosts its Attack, Sp. Atk, and Speed stats by using its own HP.' WHERE "name" = 'fillet-away';
UPDATE "move" SET "flavorText"='The user rends the target with an ethereal blade. This move''s power is boosted by 50 percent if the user is on Electric Terrain.' WHERE "name" = 'psyblade';
UPDATE "move" SET "flavorText"='The user summons a ruinous disaster. This cuts the target''s HP in half.' WHERE "name" = 'ruination';
UPDATE "move" SET "flavorText"='The user blasts the target with boiling-hot water. This move''s power is not lowered in harsh sunlight but rather boosted by 50 percent.' WHERE "name" = 'hydro-steam';
UPDATE "move" SET "flavorText"='The user performs a tackle like a raging bull. This move''s type depends on the user''s form. It can also break barriers, such as Light Screen and Reflect.' WHERE "name" = 'raging-bull';
UPDATE "move" SET "flavorText"='The user throws a rigged bouquet of flowers at the target. This attack never misses and always lands a critical hit.' WHERE "name" = 'flower-trick';
UPDATE "move" SET "flavorText"='The user tells a chillingly bad joke before switching places with a party Pokémon in waiting. This summons a snowstorm lasting five turns.' WHERE "name" = 'chilly-reception';
UPDATE "move" SET "flavorText"='The user spins the pointed part of its body at high speed to pierce the target. This attack can hit a target using a move such as Protect or Detect.' WHERE "name" = 'hyper-drill';
UPDATE "move" SET "flavorText"='The user attacks the target by showering it with water that''s so cold it saps the target''s power. This also lowers the target''s Attack stat.' WHERE "name" = 'chilling-water';
UPDATE "move" SET "flavorText"='The user swaps its Attack and Defense stats.' WHERE "name" = 'power-shift';
UPDATE "move" SET "flavorText"='The user performs an intense dance to usher in victory, boosting its Attack, Defense, and Speed stats.' WHERE "name" = 'victory-dance';
UPDATE "move" SET "flavorText"='The user hurls giant chunks of ice at the target to inflict damage. This may also make the target flinch.' WHERE "name" = 'mountain-gale';
UPDATE "move" SET "flavorText"='The user shrouds itself in water and slams into the target with its whole body to inflict damage. This also damages the user quite a lot.' WHERE "name" = 'wave-crash';
UPDATE "move" SET "flavorText"='The user swings its stone axes at the target. Stone splinters left behind by this attack float around the target.' WHERE "name" = 'stone-axe';
UPDATE "move" SET "flavorText"='Esper Wing inflicts damage and has an increased critical hit ratio. It also raises the user''s action speed.' WHERE "name" = 'esper-wing';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'psyshield-bash';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'barb-barrage';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'mystical-power';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'headlong-rush';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'bitter-malice';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'chloroblast';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'lunar-blessing';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'spin-out';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'raging-fury';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'springtide-storm';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'sandsear-storm';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'wildbolt-storm';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'bleakwind-storm';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'order-up';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'ceaseless-edge';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'population-bomb';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'tera-blast';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'electro-drift';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'spicy-extract';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'infernal-parade';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'jet-punch';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'triple-arrows';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'last-respects';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'take-heart';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'mortal-spin';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'axe-kick';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'triple-dive';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'silk-trap';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'doodle';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'glaive-rush';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'revival-blessing';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'shed-tail';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'salt-cure';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'torch-song';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'aqua-step';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'collision-course';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'kowtow-cleave';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'make-it-rain';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'dire-claw';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'shelter';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'lumina-crash';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'trailblaze';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'bitter-blade';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'combat-torque';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'blood-moon';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'dragon-cheer';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'wicked-torque';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'snowscape';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'blazing-torque';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'tachyon-cutter';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'gigaton-hammer';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'hard-press';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'electro-shot';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'burning-bulwark';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'alluring-voice';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'supercell-slam';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'fickle-beam';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'mighty-cleave';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'tera-starstorm';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'psychic-noise';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'upper-hand';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'syrup-bomb';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'malignant-chain';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'thunderclap';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'twin-beam';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'armor-cannon';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'comeuppance';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'matcha-gotcha';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'ivy-cudgel';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'aqua-cutter';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'magical-torque';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'double-shock';
UPDATE "move" SET "flavorText"='jose' WHERE "name" = 'temper-flare';
